import { Footer, Header } from '@/components'
import clsx from 'clsx'
import type { Metadata } from 'next'
import { Session } from 'next-auth'
import { Inter } from 'next/font/google'
import Providers from './Providers'
import './globals.css'
const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

interface LayoutProps {
  children: React.ReactNode
  session: Session
}

export default function RootLayout({ children, session }: LayoutProps) {
  const styles = {
    wrapper: clsx(inter.className, 'bg-black')
  }
  return (
    <html lang='en'>
      <body className={styles.wrapper}>
        <Providers session={session}>
          <Header />
          {children}
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
